name: Update Node Lambda Code
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my_ts_service
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to aws labmda
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: zip -j my_ts_service.zip ./dist/index.js
      - run: aws lambda update-function-code --function-name=my_ts_service --zip-file=fileb://my_ts_service.zip